#!/usr/bin/env python3
"""Generate username-based direct Mihomo subscription aliases for Nginx.

Remnawave intentionally authenticates public subscriptions with a short UUID.
The old s-ui endpoint used the username in ``/clash/<username>`` instead.  This
script creates an ignored, production-only Nginx include that maps active
usernames to their current Remnawave short UUID without putting those tokens in
the repository.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path


USERNAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def load_token(path: Path) -> str:
    token = os.environ.get("REMNAWAVE_API_TOKEN", "").strip()
    if token:
        return token
    return path.read_text(encoding="utf-8").strip()


def fetch_users(panel_url: str, token: str) -> list[dict]:
    request = urllib.request.Request(
        f"{panel_url.rstrip('/')}/api/users",
        headers={"Authorization": f"Bearer {token}"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Remnawave API returned HTTP {error.code}: {detail}") from error

    users = payload.get("response", {}).get("users", [])
    if not isinstance(users, list):
        raise RuntimeError("Remnawave /api/users returned an unexpected response")
    return users


def render_aliases(users: list[dict]) -> str:
    blocks: list[str] = [
        "# Generated by sync_subscription_aliases.py; do not edit.",
        "# This file contains subscription short UUIDs and is intentionally ignored by git.",
        "",
    ]
    for user in sorted(users, key=lambda item: str(item.get("username", ""))):
        username = str(user.get("username", ""))
        short_uuid = str(user.get("shortUuid", ""))
        if user.get("status") != "ACTIVE":
            continue
        if not USERNAME_RE.fullmatch(username) or not USERNAME_RE.fullmatch(short_uuid):
            continue

        for suffix in ("", ".yaml", ".yml"):
            public_path = f"/clash/{username}{suffix}"
            filename = f"{username}.yaml"
            blocks.extend(
                [
                    f"location = {public_path} {{",
                    f"    rewrite ^ /api/sub/{short_uuid}/mihomo break;",
                    "    proxy_hide_header Content-Disposition;",
                    f"    add_header Content-Disposition 'attachment; filename=\"{filename}\"' always;",
                    "    proxy_pass http://127.0.0.1:3000;",
                    "    proxy_http_version 1.1;",
                    "    proxy_set_header Host $host;",
                    "    proxy_set_header X-Real-IP $remote_addr;",
                    "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                    "    proxy_set_header X-Forwarded-Proto https;",
                    "    proxy_connect_timeout 10s;",
                    "    proxy_read_timeout 300s;",
                    "}",
                    "",
                ]
            )
    return "\n".join(blocks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--panel-url", default="https://panel-verizon.bigpandas.top")
    parser.add_argument(
        "--token-file",
        type=Path,
        default=Path("/root/code/us-public/remnawave/.api-token"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("subscription-aliases.conf"),
    )
    args = parser.parse_args()

    token = load_token(args.token_file)
    content = render_aliases(fetch_users(args.panel_url, token))
    args.output.write_text(content, encoding="utf-8")
    args.output.chmod(0o600)
    print(f"Generated {args.output}.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
