server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name us.bigpandas.top;

    root /var/www/html;
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name us.bigpandas.top;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
